-- Seed: the questions each machine type asks.
--
-- The snacks sets reproduce shared/constants.js exactly, so Pods already in
-- service ask precisely what they asked before. Idempotent.

PRAGMA foreign_keys = ON;

INSERT INTO question_sets (set_id, machine_type, kind) VALUES ('snacks_feedback', 'snacks', 'feedback') ON CONFLICT(set_id) DO NOTHING;
INSERT INTO question_sets (set_id, machine_type, kind) VALUES ('snacks_complaint', 'snacks', 'complaint') ON CONFLICT(set_id) DO NOTHING;
INSERT INTO question_sets (set_id, machine_type, kind) VALUES ('coffee_feedback', 'coffee', 'feedback') ON CONFLICT(set_id) DO NOTHING;
INSERT INTO question_sets (set_id, machine_type, kind) VALUES ('coffee_complaint', 'coffee', 'complaint') ON CONFLICT(set_id) DO NOTHING;

-- Snacks, feedback: unchanged from the hardcoded form.
INSERT INTO questions (question_id, set_id, qkey, position, type, kicker, title, hint, options, extra_placeholder, optional, maps_to) VALUES ('snacks_feedback_wanted', 'snacks_feedback', 'wanted', 10, 'multi', 'Your call', 'What should we stock here?', 'Pick as many as you like.', '[{"value": "chips", "label": "Chips & namkeen"}, {"value": "chocolate", "label": "Chocolate & candy"}, {"value": "cold_drink", "label": "Cold drinks"}, {"value": "water", "label": "Water"}, {"value": "coffee_tea", "label": "Coffee & tea"}, {"value": "healthy", "label": "Healthy snacks"}, {"value": "protein", "label": "Protein & fitness"}, {"value": "ready_meal", "label": "Ready meals"}, {"value": "other", "label": "Something else"}]', 'Any particular brand or item?', 1, 'wanted_categories') ON CONFLICT(question_id) DO NOTHING;
INSERT INTO questions (question_id, set_id, qkey, position, type, kicker, title, hint, options, extra_placeholder, optional, maps_to) VALUES ('snacks_feedback_price', 'snacks_feedback', 'price', 20, 'single', 'Be honest', 'How do the prices feel?', NULL, '[{"value": "expensive", "label": "Too expensive"}, {"value": "fair", "label": "About right"}, {"value": "good", "label": "Good value"}]', NULL, 1, 'price_feel') ON CONFLICT(question_id) DO NOTHING;
INSERT INTO questions (question_id, set_id, qkey, position, type, kicker, title, hint, options, extra_placeholder, optional, maps_to) VALUES ('snacks_feedback_usage', 'snacks_feedback', 'usage', 30, 'single', 'Last one', 'How often do you use this Pod?', NULL, '[{"value": "first_time", "label": "First time"}, {"value": "sometimes", "label": "Now and then"}, {"value": "weekly", "label": "Weekly"}, {"value": "daily", "label": "Daily"}]', NULL, 1, 'usage_freq') ON CONFLICT(question_id) DO NOTHING;

-- Snacks, complaint.
INSERT INTO questions (question_id, set_id, qkey, position, type, kicker, title, hint, options, extra_placeholder, optional, maps_to) VALUES ('snacks_complaint_issue', 'snacks_complaint', 'issue', 10, 'single', 'Sorry about that', 'What went wrong?', NULL, '[{"value": "no_dispense", "label": "Paid but nothing came out", "payment": true}, {"value": "wrong_item", "label": "Wrong item dispensed"}, {"value": "damaged_item", "label": "Item damaged or expired"}, {"value": "double_charge", "label": "Charged twice", "payment": true}, {"value": "payment_failed", "label": "Payment failed", "payment": true}, {"value": "machine_fault", "label": "Machine not working"}, {"value": "other", "label": "Something else"}]', NULL, 0, 'issue_type') ON CONFLICT(question_id) DO NOTHING;
INSERT INTO questions (question_id, set_id, qkey, position, type, kicker, title, hint, options, extra_placeholder, optional, maps_to) VALUES ('snacks_complaint_when', 'snacks_complaint', 'when', 20, 'single', 'Timing', 'When did it happen?', NULL, '[{"value": "just_now", "label": "Just now"}, {"value": "today", "label": "Earlier today"}, {"value": "earlier", "label": "Yesterday or before"}]', NULL, 0, 'occurred_when') ON CONFLICT(question_id) DO NOTHING;

-- Coffee, feedback.
INSERT INTO questions (question_id, set_id, qkey, position, type, kicker, title, hint, options, extra_placeholder, optional, maps_to) VALUES ('coffee_feedback_strength', 'coffee_feedback', 'strength', 10, 'single', 'The important bit', 'How was the strength?', NULL, '[{"value": "weak", "label": "Too weak"}, {"value": "right", "label": "Just right"}, {"value": "strong", "label": "Too strong"}]', NULL, 1, NULL) ON CONFLICT(question_id) DO NOTHING;
INSERT INTO questions (question_id, set_id, qkey, position, type, kicker, title, hint, options, extra_placeholder, optional, maps_to) VALUES ('coffee_feedback_temperature', 'coffee_feedback', 'temperature', 20, 'single', 'Served right', 'And the temperature?', NULL, '[{"value": "cold", "label": "Not hot enough"}, {"value": "right", "label": "Just right"}, {"value": "hot", "label": "Too hot"}]', NULL, 1, NULL) ON CONFLICT(question_id) DO NOTHING;
INSERT INTO questions (question_id, set_id, qkey, position, type, kicker, title, hint, options, extra_placeholder, optional, maps_to) VALUES ('coffee_feedback_wanted_drinks', 'coffee_feedback', 'wanted_drinks', 30, 'multi', 'Your call', 'What else would you like to see?', 'Pick as many as you like.', '[{"value": "more_coffee", "label": "More coffee styles"}, {"value": "tea", "label": "Tea"}, {"value": "plant_milk", "label": "Oat or soy milk"}, {"value": "less_sugar", "label": "Sugar control"}, {"value": "larger_cup", "label": "A larger cup"}, {"value": "snacks", "label": "Something to eat"}, {"value": "other", "label": "Something else"}]', 'Anything in particular?', 1, NULL) ON CONFLICT(question_id) DO NOTHING;
INSERT INTO questions (question_id, set_id, qkey, position, type, kicker, title, hint, options, extra_placeholder, optional, maps_to) VALUES ('coffee_feedback_price', 'coffee_feedback', 'price', 40, 'single', 'Be honest', 'How do the prices feel?', NULL, '[{"value": "expensive", "label": "Too expensive"}, {"value": "fair", "label": "About right"}, {"value": "good", "label": "Good value"}]', NULL, 1, 'price_feel') ON CONFLICT(question_id) DO NOTHING;
INSERT INTO questions (question_id, set_id, qkey, position, type, kicker, title, hint, options, extra_placeholder, optional, maps_to) VALUES ('coffee_feedback_usage', 'coffee_feedback', 'usage', 50, 'single', 'Last one', 'How often do you use this machine?', NULL, '[{"value": "first_time", "label": "First time"}, {"value": "sometimes", "label": "Now and then"}, {"value": "weekly", "label": "Weekly"}, {"value": "daily", "label": "Daily"}]', NULL, 1, 'usage_freq') ON CONFLICT(question_id) DO NOTHING;

-- Coffee, complaint. Values match the snacks ones because
-- submissions.issue_type has a CHECK on them; only the wording differs.
INSERT INTO questions (question_id, set_id, qkey, position, type, kicker, title, hint, options, extra_placeholder, optional, maps_to) VALUES ('coffee_complaint_issue', 'coffee_complaint', 'issue', 10, 'single', 'Sorry about that', 'What went wrong?', NULL, '[{"value": "no_dispense", "label": "Paid but no drink came out", "payment": true}, {"value": "wrong_item", "label": "Wrong drink"}, {"value": "damaged_item", "label": "Drink was cold, weak or spilled"}, {"value": "double_charge", "label": "Charged twice", "payment": true}, {"value": "payment_failed", "label": "Payment failed", "payment": true}, {"value": "machine_fault", "label": "Machine not working"}, {"value": "other", "label": "Something else"}]', NULL, 0, 'issue_type') ON CONFLICT(question_id) DO NOTHING;
INSERT INTO questions (question_id, set_id, qkey, position, type, kicker, title, hint, options, extra_placeholder, optional, maps_to) VALUES ('coffee_complaint_when', 'coffee_complaint', 'when', 20, 'single', 'Timing', 'When did it happen?', NULL, '[{"value": "just_now", "label": "Just now"}, {"value": "today", "label": "Earlier today"}, {"value": "earlier", "label": "Yesterday or before"}]', NULL, 0, 'occurred_when') ON CONFLICT(question_id) DO NOTHING;
